theme: minima
title: "Situated Language and Perception Research Group"
author: " "
description: " "
header_pages:
  - index.md
  - meetings.md
  - courses.md
    sub_pages:
      - rom.md
      - apl.md
