theme: minima
title: "Situated Language and Perception Research Group"
author: " "
description: " "
header_pages:
  - path: index.md
  - path: meetings.md
  - path: courses.md
    sub_pages:
      - courses/rom/rom.md
      - courses/apl/apl.md
      - courses/csoc/csoc.md
      - courses/ml-vl/ml-vl.md
  - path: masters-projects.md
    sub_pages:
      - masters-projects/situated-agents.md
      - masters-projects/spatial-language.md
      - masters-projects/co-reference.md
      - masters-projects/virtual-assistants.md
      - masters-projects/explainable-ai.md
