theme: minima
title: "Situated Language and Perception Research Group"
author: " "
description: " "
header_pages:
  - path: index.md
  - path: meetings.md
  - path: courses.md
    sub_pages:
      - rom.md
      - apl.md
